### PR TITLE
Cnv by gene

### PR DESCRIPTION
**Pull request by Graeme-Smith**
A form, subform & query to allow the array team to search for CNVs by Gene.  

The VBA code dynamically creates a query to replace the PlaceHolderQuery, depending upon the gene selected.  This SQL query  calculates which CNVs are overlapping the specified region.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: all files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

___
*[forms/s09_CNVsByGene, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_ubmrEEl4hmTpqQk8y:-M_ubmrF3LGRSBY0pjYm:b5pa39v) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGene#L31)):*
> ```
> End Sub
> 
> ''dgv
> ```

could you add some comments please. What is this code doing?
___
*[forms/s09_CNVsByGeneDropDown, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_uc-a86fdMl_N2uFdM:-M_uc-a86fdMl_N2uFdN:b268cqe) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGeneDropDown#L31)):*
> ```
> 
> 
> Me.s09_CNVsByGene.SourceObject = "Query.PlaceHolderQuery"
> ```

Are these variables being used?

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: all files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[forms/s09_CNVsByGene, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_ubmrEEl4hmTpqQk8y:-M_udEcG8Knl6zP2hMb8:b-x72my9) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGene#L31)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

could you add some comments please. What is this code doing?
</blockquote></details>

This is legacy code from the form I based this one off, basically double clicking on the Start column will open a genome browser to that location.
___
*[forms/s09_CNVsByGeneDropDown, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_uc-a86fdMl_N2uFdM:-M_uchPZAQMkmPWIntA7:b-v51o51) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGeneDropDown#L31)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Are these variables being used? 
</blockquote></details>

These variables are used to refresh the datasource - PlaceHolderQuery - when the combobox selection is refreshed.

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[forms/s09_CNVsByGene, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_ubmrEEl4hmTpqQk8y:-M_uidPZ4yXtVnzAeOj_:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGene#L31)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

This is legacy code from the form I based this one off, basically double clicking on the Start column will open a genome browser to that location.
</blockquote></details>

Done.

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[forms/s09_CNVsByGeneDropDown, line 31 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/667#-M_uc-a86fdMl_N2uFdM:-M_uiiDW5sI_QfIuqUyA:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/79fe7655461f0cf9df8c69485627b019769b9e78/forms/s09_CNVsByGeneDropDown#L31)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

These variables are used to refresh the datasource - PlaceHolderQuery - when the combobox selection is refreshed.
</blockquote></details>

Done.

**Review by natashapinto — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
