### PR TITLE
Add frax queries

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651)* status: 0 of 7 files reviewed, 1 unresolved discussion

___
*[forms/6101 FRAXlist SQL, line 3 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/651#-MUEv6Fm0eH7BqxSd70d:-MUEv6Fm0eH7BqxSd70e:bwyizb0) ([raw file](https://github.com/moka-guys/moka-fe/blob/8a4fe5b9e2fac33bac0e2d504af79f3bda32ca6c/forms/6101 FRAXlist SQL#L3)):*
> ```
> tYes.Disorder) Like "Fragile X Syndrome*")
> ```
This has been changed from disorder="Fragile X Syndrome"

**Review by aledj2 — COMMENTED** [review]
Awaiting UAT before code review

> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651#-:-MUEvBxy-1Q7L7xiMLSC:b-evmt73)* status: 0 of 7 files reviewed, 1 unresolved discussion

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651)* status: 0 of 7 files reviewed, 3 unresolved discussions

___
*[queries/s_FraXDiagnosticTests, line 3 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/651#-MUK4mHw2bOmuoRy9gD4:-MUK4mHw2bOmuoRy9gD5:boyfdvx) ([raw file](https://github.com/moka-guys/moka-fe/blob/8a4fe5b9e2fac33bac0e2d504af79f3bda32ca6c/queries/s_FraXDiagnosticTests#L3)):*
> ```
>  like "Fragile X Syndrome*
> ```
This has been changed
___
*[queries/s_FraXStraight, line 3 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/651#-MUK4jZI99kJ7xmFsGZz:-MUK4jZI99kJ7xmFsG_-:b-q5f22x) ([raw file](https://github.com/moka-guys/moka-fe/blob/8a4fe5b9e2fac33bac0e2d504af79f3bda32ca6c/queries/s_FraXStraight#L3)):*
> ```
> ) like "Fragile X Syndrome*")
> ```
This has been changed

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

**Review by Graeme-Smith — APPROVED** [review]
> Dismissed @aledj2 from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/651)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
