### PR TITLE
Improve WES dashboard speed, enable trio filtering 

### PR DESCRIPTION
**Pull request by ErinPeat**
- Update 87020 ExomeLab to improve speed by removing amount of times query is run on subform on initial loading 
-Update 87020 ExomeLab to filter non-probands who have certain statuses when the WES Trio user group is selected
-Update 87020 ExomeLab to filter non-probands who have certain statuses when the status drop down are selected
-Display a warning to users of the WES Dashboard to ensure they know some non-probands will not show upon selecting certain things
- Change query in s87020_ExomeLabList to correct query for this form (possibly not updated on GitHub in the past)
- Keep query in s87020_ListWESSamples the same, updates were made and then changed back

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/645)

- Add New query  s87020_ListWESSamples_view to access the view of this query created. Speeds up dashboard returns. This is used for all the filtering etc on the form and then s87020_ListWESSamples query is used when editing or updating records.

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/645)* status: all files reviewed, 3 unresolved discussions (waiting on @ErinPeat)

___
*[forms/87020 ExomeLab, line 24 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKdz6VR6O2HM_1QVt54:-MKdz6VSCPDXlxTLBn6i:brawyui) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L24)):*
> ```
> Me.txt_displayed = "SELECT A FILTER TO VIEW CASES"
> update_referral CallBtnView:=False
> 'Ensures that the btn_ViewAll_Click function is not called in this instance, as part of the update_referral function
> ```

Is this comment meant to go above the code?
___
*[forms/87020 ExomeLab, line 49 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKe1zLx6IouiVrZlRy-:-MKe1zLx6IouiVrZlRy0:bugget9) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L49)):*
> ```
> 'FilteringTriosStatusBoolean facilitates filtering and setting the text displayed on the dashboard to users
> 
> If Me.cmb_StatusView = "1202218807" Or Me.cmb_StatusView = "1202218808" Or Me.cmb_StatusView = "1202218809" Or Me.cmb_StatusView = "1202218810" Or Me.cmb_StatusView = "1202218811" Or Me.cmb_StatusView = "1202218812" Or Me.cmb_StatusView = "1202218813" Or Me.cmb_StatusView = "1202218814" Or Me.cmb_StatusView = "1202218815" Or Me.cmb_StatusView = "1202218816" Or Me.cmb_StatusView = "1202218822" Or Me.cmb_StatusView = "1202218857" Or Me.cmb_StatusView = "1202218863" Or Me.cmb_StatusView = "1202218864" Or Me.cmb_StatusView = "1202218865" Or Me.cmb_StatusView = "1202218866" Or Me.cmb_StatusView = "1202218867" Or Me.cmb_StatusView = "1202218868" Or Me.cmb_StatusView = "1202218869" Or Me.cmb_StatusView = "1202218870" Or Me.cmb_StatusView = "2" Or Me.cmb_StatusView = "4" Then
> ```

Could this be written as If me.cmb_StatusView in (list of status ids)?
___
*[forms/87020 ExomeLab, line 79 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKe37hTCBAF-Yq6elh8:-MKe37hTCBAF-Yq6elh9:b-cuhoeu) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L79)):*
> ```
> ' Deselct all selected samples
> Check_selectAll.Value = False
> ```

remove additional empty lines

**Review by ErinPeat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/645)* status: all files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[forms/87020 ExomeLab, line 24 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKdz6VR6O2HM_1QVt54:-MKevi2L9-mieM2T6296:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L24)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Is this comment meant to go above the code?
</blockquote></details>

Done.
___
*[forms/87020 ExomeLab, line 49 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKe1zLx6IouiVrZlRy-:-MKeMera6Y-67l8juqlU:b-zfqhd5) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L49)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Could this be written as If me.cmb_StatusView in (list of status ids)?
</blockquote></details>

I've just tried and VBA doesn't like the 'in' and expects 'then', I believe you can only evaluate a single condition to be true each time. Can try to create an ArrayList (which is an external library so will need additional installation)  or a collection but each element has to be declared individually like so StatusArrayList.Add = "XXX" so I feel like that will take up as much space as this does. Let me know if you'd like me to try ArrayList out or collection out instead. 
___
*[forms/87020 ExomeLab, line 79 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKe37hTCBAF-Yq6elh8:-MKewQyf30iuZNxRBZww:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L79)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

remove additional empty lines
</blockquote></details>

Done.

**Review by natashapinto — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/645)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[forms/87020 ExomeLab, line 49 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/645#-MKe1zLx6IouiVrZlRy-:-MKf03JF3DO8Mnhvz03O:b-akkycz) ([raw file](https://github.com/moka-guys/moka-fe/blob/88dc47fc61baa47246d9488b8bc68e751d5e20d8/forms/87020 ExomeLab#L49)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

I've just tried and VBA doesn't like the 'in' and expects 'then', I believe you can only evaluate a single condition to be true each time. Can try to create an ArrayList (which is an external library so will need additional installation)  or a collection but each element has to be declared individually like so StatusArrayList.Add = "XXX" so I feel like that will take up as much space as this does. Let me know if you'd like me to try ArrayList out or collection out instead. 
</blockquote></details>

Ok, lets just stick with this format then

**Comment by ErinPeat** [comment]
New approach taken to coding for this task. New PR to be opened.

**Pull request closed without merging**
