### PR TITLE
Array audits

### PR DESCRIPTION
**Pull request by RachelDuffin**
Add new list in the array menu where users can enter initials and all cases authorised by that user (both as first and second authoriser) will appear in a table (based on '9302 MyChecks').

Add new form (based on '989 ArrayAnalysisChecks') to the array menu to display number of authorised cases (both as first and second authoriser) for a set of users.

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642#-:-MJ7WihA2UkmyUfQRFyi:bweg3f8)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @aledj2)

**Review by aledj2 — CHANGES_REQUESTED** [review]
looks good! a few questions for my own interest and one suggestion to change - feel free to ignore if you wish , is fine to go as is

> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642#-:-MJ7_K4oDblIul67ez7P:brays1k)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[forms/989 ArrayAnalysisAuthorised, line 19 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7Yyjn1HJGm7sZsSNw:-MJ7Yyjn1HJGm7sZsSNx:bfnncof) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L19)):*
> ```
>     & "(SELECT ResultCode_1.ResultCode, Checker.Initials " _
>     & "FROM ((((ArrayTest INNER JOIN Checker ON ArrayTest.Check4ID = Checker.Check1ID) INNER JOIN ResultCode ON ArrayTest.ArrayResultCodeID = ResultCode.ResultCodeID) INNER JOIN Patients ON ArrayTest.InternalPatientID = Patients.InternalPatientID) INNER JOIN ResultCode AS ResultCode_1 ON Patients.OverallResultCodeID = ResultCode_1.ResultCodeID) INNER JOIN Referral ON ArrayTest.ReferralID = Referral.ReferralID " _
>     & "WHERE (((Checker.Initials) Like 'KJM' Or (Checker.Initials) Like 'KM' Or (Checker.Initials) Like 'CD' Or (Checker.Initials) Like 'SCH' Or (Checker.Initials) Like 'CO' Or (Checker.Initials) Like 'AB' Or (Checker.Initials) Like 'SB') " _
> ```

could we set the where clause as a string that can be included in the query, so if it's edited (eg adding or removing users) that only needs to be done once. eg 
user_string = "WHERE (((Checker.Initials) Like 'KJM' Or (Checker.Initials) Like 'KM' Or (Checker.Initials) Like 'CD' Or (Checker.Initials) Like 'SCH' Or (Checker.Initials) Like 'CO' Or (Checker.Initials) Like 'AB' Or (Checker.Initials) Like 'SB')" and the query would be "from ... " & user_string & "AND ..."

This could be expanded to the entire where clause if appropriate, but the main thing is to make the form easy to update as/when staff leave so prob best to just extract out this bit
___
*[forms/989 ArrayAnalysisAuthorised, line 21 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7ZZkr-BWreUVlJw7l:-MJ7ZZkr-BWreUVlJw7m:b-nlmatv) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L21)):*
> ```
>     & "WHERE (((Checker.Initials) Like 'KJM' Or (Checker.Initials) Like 'KM' Or (Checker.Initials) Like 'CD' Or (Checker.Initials) Like 'SCH' Or (Checker.Initials) Like 'CO' Or (Checker.Initials) Like 'AB' Or (Checker.Initials) Like 'SB') " _
>     & "AND ((arraytest.Service) = True) And ((Referral.ReferralID) = " & Me.referral_combo & ") And ((arraytest.ArrayResultDate) >= #" & start_date_formatted & "#) And ((arraytest.ArrayResultDate) <= #" & end_date_formatted & "#)) " _
>     & "UNION ALL " _
> ```

just for my interest, what does union all do?
___
*[forms/989 ArrayAnalysisAuthorised, line 27 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7_AjA6eqIJKQ9asXD:-MJ7_AjA6eqIJKQ9asXE:b-lofei) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L27)):*
> ```
>     & "AND ((arraytest.Service) = True) And ((Referral.ReferralID) = " & Me.referral_combo & ") And ((arraytest.ArrayResultDate) >= #" & start_date_formatted & "#) And ((arraytest.ArrayResultDate) <= #" & end_date_formatted & "#))) " _
>     & "GROUP BY ResultCode_1.ResultCode " _
>     & "PIVOT Checker.Initials;"
> ```

what does pivot do?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[forms/989 ArrayAnalysisAuthorised, line 19 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7Yyjn1HJGm7sZsSNw:-MJ7bOQ4DvKjz4thnuG6:b-be3qhs) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

could we set the where clause as a string that can be included in the query, so if it's edited (eg adding or removing users) that only needs to be done once. eg 
user_string = "WHERE (((Checker.Initials) Like 'KJM' Or (Checker.Initials) Like 'KM' Or (Checker.Initials) Like 'CD' Or (Checker.Initials) Like 'SCH' Or (Checker.Initials) Like 'CO' Or (Checker.Initials) Like 'AB' Or (Checker.Initials) Like 'SB')" and the query would be "from ... " & user_string & "AND ..."

This could be expanded to the entire where clause if appropriate, but the main thing is to make the form easy to update as/when staff leave so prob best to just extract out this bit
</blockquote></details>

Good idea, I will make this change. 
___
*[forms/989 ArrayAnalysisAuthorised, line 21 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7ZZkr-BWreUVlJw7l:-MJ7aGSAECb03ZQItSZv:b-xci6w3) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L21)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

just for my interest, what does union all do?
</blockquote></details>

UNION ALL combines the result set of two or more SELECT statements and allows duplicate values. So in this case I used it because I am trying to combine the tests where that user was authoriser 1 and tests where the user was authoriser 2 into a single table so that the initials sit within a single field (as opposed to a field for authoriser 1 and field for authoriser 2) and can then be grouped by their result code and counted. 
___
*[forms/989 ArrayAnalysisAuthorised, line 27 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7_AjA6eqIJKQ9asXD:-MJ7apKQ8eDU-D6WGRJX:b5ww4ul) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L27)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what does pivot do?
</blockquote></details>

PIVOT takes multiple values from a single column to use these as column headers - so in this case uses the initials in Checker.Initials as the new column headers. (Effectively rotates the table)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2 and @RachelDuffin)

___
*[forms/989 ArrayAnalysisAuthorised, line 21 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7ZZkr-BWreUVlJw7l:-MJ7cunH2Yf55QBm0eh7:bhlq0hx) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L21)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

UNION ALL combines the result set of two or more SELECT statements and allows duplicate values. So in this case I used it because I am trying to combine the tests where that user was authoriser 1 and tests where the user was authoriser 2 into a single table so that the initials sit within a single field (as opposed to a field for authoriser 1 and field for authoriser 2) and can then be grouped by their result code and counted. 
</blockquote></details>

is that needed when the columns in the select are named the same? does union remove duplicates? 
___
*[forms/989 ArrayAnalysisAuthorised, line 27 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7_AjA6eqIJKQ9asXD:-MJ7dBxIBHOL7xctppuJ:bvij09x) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L27)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

PIVOT takes multiple values from a single column to use these as column headers - so in this case uses the initials in Checker.Initials as the new column headers. (Effectively rotates the table)
</blockquote></details>

so the output is one row, with a value for each user?

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[forms/989 ArrayAnalysisAuthorised, line 21 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7ZZkr-BWreUVlJw7l:-MJ7gfYbEmjuVlySfULA:b-gmdomr) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L21)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is that needed when the columns in the select are named the same? does union remove duplicates? 
</blockquote></details>

The columns are named the same in the select because they are two separate select statements. I couldn't find a way to have it as a single select statement as ArrayTest.Check4ID (authoriser 1) and ArrayTest.Check5ID (authoriser 2) are two columns in the same table, and I needed a way to combine them into one to get at total count of the number of times a user has authorised case results. If there is an easier/better way to do it I can change it. 

UNION removes duplicates, UNION ALL does not. Also UNION doesn't work with text columns whereas UNION ALL does. 
___
*[forms/989 ArrayAnalysisAuthorised, line 27 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7_AjA6eqIJKQ9asXD:-MJ7hktn8o_qbc02B5BM:b9hf5mh) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L27)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

so the output is one row, with a value for each user?
</blockquote></details>

The output is multiple rows, with a row per result (ResultCode_1.ResultCodeID).

**Review by RachelDuffin — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[forms/989 ArrayAnalysisAuthorised, line 19 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/642#-MJ7Yyjn1HJGm7sZsSNw:-MJS-KAs8RcWwVUHLLFX:b7ieiek) ([raw file](https://github.com/moka-guys/moka-fe/blob/1742e61b792401a7ee8a2a25182784de5d2b905d/forms/989 ArrayAnalysisAuthorised#L19)):*
<details><summary><i>Previously, RachelDuffin wrote…</i></summary><blockquote>

Good idea, I will make this change. 
</blockquote></details>

Change added - user list now a separate string.

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/642#-:-MJSJkfP3agvicRF5Zfx:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
