### PR TITLE
Consumables url

### PR DESCRIPTION
**Pull request by Graeme-Smith**
Added a field for a URL to contain links to manufacturers websites as per ticket INC0073185
- Updated SQL to pull in field CompanyURL
- Added VBA code so url is opened on double click

---
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)

### CODE REVIEW

**Review by ErinPeat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[forms/33 Inventory Consumables, line 7 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/666#-M_fsdXvAkkeAwEDRbLt:-M_fsdXvAkkeAwEDRbLu:b-w4o5wd) ([raw file](https://github.com/moka-guys/moka-fe/blob/2390619020bcb5915d4907ff62df08cd3306a197/forms/33 Inventory Consumables#L7)):*
> ```
> End Sub
> 
> Private Sub Command23_Click()
> ```

Some comments perhaps? We spoke about having a little doc string at the top of moka forms to explain briefly what they do as well?

**Comment by Graeme-Smith** [comment]
Hi Erin, I've added a doc string to the function I added - this is also the first commit of some legacy code.

**Review by ErinPeat — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

**Review by ErinPeat — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[forms/33 Inventory Consumables, line 7 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/666#-M_fsdXvAkkeAwEDRbLt:-M_tsZtAE_wg38npyPwC:b-tmqtb2) ([raw file](https://github.com/moka-guys/moka-fe/blob/2390619020bcb5915d4907ff62df08cd3306a197/forms/33 Inventory Consumables#L7)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Some comments perhaps? We spoke about having a little doc string at the top of moka forms to explain briefly what they do as well? 
</blockquote></details>

Comment responded too

**Review by ErinPeat — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: all files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

**Review by Graeme-Smith — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: all files reviewed, 1 unresolved discussion (waiting on @ErinPeat)

___
*[forms/33 Inventory Consumables, line 7 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/666#-M_fsdXvAkkeAwEDRbLt:-M_tt7X24G-5aSMS3YXM:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/2390619020bcb5915d4907ff62df08cd3306a197/forms/33 Inventory Consumables#L7)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Comment responded too
</blockquote></details>

Done.

**Review by ErinPeat — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Graeme-Smith)

**Pull request merged**
